# Generated by Django 2.2.2 on 2019-07-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190706_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='TITLE', max_length=200),
        ),
    ]
