# Generated by Django 2.2.2 on 2019-07-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='DESCRIPTION', max_length=300),
        ),
    ]
