# Generated by Django 2.2.2 on 2019-07-07 04:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_bookreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
